# Generated by Django 4.0.8 on 2022-12-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='path',
            new_name='category',
        ),
    ]
