# Generated by Django 4.0.8 on 2022-12-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_path_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resnet',
            name='categories',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
